### ISSUE TITLE
Configuration mode disappear

### ISSUE THREAD

**Issue by j3zh1** [notpeelz/reshade-xhair#10]
Hello,
Reshade updated and there is not 'use mode' or 'configuration mode' buttons in 'Settings' tab now. 
When I tried to change the crosshair color, the log said that there are some warnings in 'xhair.fx' 452, 496 and 517 due to implicit truncation of vector type. How can I fix it? 
Thanks

**Comment by LouisTakePILLz** [comment]
Thanks. I'll update the readme soon.For the 2nd issue, you can safely ignore it.On Jan 11, 2021 12:06 AM, J3rrysama <notifications@github.com> wrote:
Hello,
Reshade updated and there is not 'use mode' or 'configuration mode' buttons in 'Settings' tab now.
When I tried to change the crosshair color, the log said that there are some warnings in 'xhair.fx' 452, 496 and 517 due to implicit truncation of vector type. How can I fix it?
Thanks

**Comment by notpeelz** [comment]
Thanks. I'll update the readme soon.

For the 2nd issue, you can safely ignore it.
